name: CI con SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Compilar y probar
        run: mvn -B clean verify --no-transfer-progress

      - name: Analizar con SonarQube Cloud
        if: ${{ secrets.SONAR_TOKEN != '' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B sonar:sonar             -Dsonar.host.url=https://sonarcloud.io             -Dsonar.token=${SONAR_TOKEN}             --no-transfer-progress
